id = "doc-comment"
name = "Documentation Comments"
version = "0.0.1"
schema_version = 1
authors = ["LAPORTE Cl√©ment <clem@etik.com>"]
description = "Zed Extension for documentation comments (Doxygen, Javadoc, and similar notation)"
repository = ""
